import test from 'node:test';import assert from 'node:assert/strict';import {deterministicBlueprint,canonical,pdf,titles,validBlueprint} from '../api/core.mjs';import {readFile} from 'node:fs/promises'
import generateHandler from '../api/generate.mjs';import pdfHandler from '../api/pdf.mjs';import emailHandler from '../api/email.mjs';import contactHandler from '../api/contact.mjs'
const source=await readFile('src/main.ts','utf8'),css=await readFile('src/styles.css','utf8'),html=await readFile('index.html','utf8'),build=await readFile('scripts/build.mjs','utf8'),core=await readFile('api/core.mjs','utf8');const bp=deterministicBlueprint({business:'A useful company',audience:'independent founders'})
test('five workshops ask only strategy-shaping questions',()=>{for(const name of titles)assert.match(source,new RegExp(`title:'${name}'`));const ids=[...source.matchAll(/q\('([^']+)'/g)].map(x=>x[1]);assert.equal(ids.length,15);assert.equal(new Set(ids).size,15);assert.equal(ids.length/titles.length,3);for(const id of ids)assert.match(core,new RegExp(`'${id}'`))})
test('journey is conversational and one question per screen',()=>{assert.match(source,/FIVE FOCUSED STRATEGY CONVERSATIONS/);assert.match(source,/ABOUT \$\{remaining\} MIN LEFT/);assert.match(source,/← Back/);assert.match(source,/Saves automatically/);assert.equal((source.match(/id=\"answer\"/g)||[]).length,1);assert.match(source,/function intro/);assert.match(source,/function bridge/)})
test('answers persist, recover safely and resume',()=>{assert.match(source,/localStorage\.setItem/);assert.match(source,/try\{const x=JSON\.parse/);assert.match(source,/function resume/);assert.match(source,/addEventListener\('input'/)})
test('report uses the four-part consulting structure',()=>{assert.equal(bp.sections.length,5);assert.deepEqual(bp.sections.map(x=>x.title),titles);assert(validBlueprint(bp));for(const s of bp.sections)assert.deepEqual(Object.keys(s),['title','observation','insight','recommendation','immediateAction']);for(const label of ['Observation','Insight','Recommendation','Immediate Action'])assert.match(source,new RegExp(label))})
test('engine connects workshops into decisions and selective services',()=>{assert(bp.patterns.length);assert.equal(bp.strategicSummary.length,3);assert.equal(bp.topPriorities.length,5);assert.deepEqual(Object.keys(bp.actionPlan),['weeks1to2','weeks3to6','weeks7to12']);assert(bp.recommendedServices.length<=2);for(const label of ["Daniel's View",'Top 5 Priorities','90-Day Plan','Where Daniel can help'])assert.match(source,new RegExp(label,'i'))})
test('PDF preserves the canonical report',()=>{const output=pdf(bp).toString();assert.match(output,/Your Brand Blueprint/);assert.match(output,/\/Count 8/);assert.match(output,/INSIGHT/);assert.match(output,/90-Day Action Plan/);assert.equal(canonical(bp),canonical(JSON.parse(JSON.stringify(bp))))})
test('email uses the canonical payload',()=>{assert.match(core,/validBlueprint/);assert.match(source,/blueprint:bp/);assert.match(source,/\/api\/email/);assert.match(source,/data-email-form/);assert.match(source,/Sending…/)})
test('responsive premium layouts and product states are present',()=>{assert.match(css,/@media\(max-width:760px\)/);assert.match(css,/report-section dl/);assert.match(css,/question-meta/);assert.match(css,/email-dialog/);assert.match(source,/data-contact/);assert.match(source,/Preparing PDF…/)})
test('production HTML references compiled assets',()=>{assert.match(html,/\/assets\/styles\.css/);assert.match(html,/\/assets\/main\.js/);assert.match(build,/dist\/assets\/styles\.css/)})
test('accessibility affordances are present',()=>{assert.match(source,/Skip to content/);assert.match(source,/role=\"progressbar\"/);assert.match(source,/role=\"alert\"/);assert.match(css,/:focus-visible/)})
const invoke=async(handler,{method='POST',body={}}={})=>{let status=200,payload,headers={};const req={method,body};const res={status(code){status=code;return this},json(value){payload=value;return this},send(value){payload=value;return this},setHeader(key,value){headers[key]=value}};await handler(req,res);return{status,payload,headers}}
test('API errors are explicit',async()=>{assert.equal((await invoke(generateHandler,{method:'GET'})).status,405);assert.equal((await invoke(generateHandler,{body:{}})).status,400);assert.equal((await invoke(pdfHandler,{body:{}})).status,400);assert.equal((await invoke(emailHandler,{body:{email:'bad'}})).status,400);assert.equal((await invoke(contactHandler,{body:{}})).status,400)})
test('generation, PDF and consultation complete contracts',async()=>{const generated=await invoke(generateHandler,{body:{answers:{audience:'founders'}}});assert.equal(generated.status,200);assert(validBlueprint(generated.payload));const document=await invoke(pdfHandler,{body:{blueprint:generated.payload}});assert.equal(document.status,200);assert.equal(document.headers['content-type'],'application/pdf');assert(document.payload.subarray(0,4).equals(Buffer.from('%PDF')));assert.equal((await invoke(contactHandler,{body:{name:'Alex',email:'a@b.co',message:'Strategy discussion'}})).status,200)})
test('scoring remains absent',()=>{assert.doesNotMatch(source,/score\s*[=:]/i);assert.doesNotMatch(core,/score\s*[=:]/i)})
