import test from 'node:test';import assert from 'node:assert/strict';import {deterministicBlueprint,canonical,pdf,titles,validBlueprint} from '../api/core.mjs';import {readFile} from 'node:fs/promises'
import generateHandler from '../api/generate.mjs';import pdfHandler from '../api/pdf.mjs';import emailHandler from '../api/email.mjs';import contactHandler from '../api/contact.mjs'
import {persistFirstBlueprintInterpretation,InterpretationConflictError} from '../api/first-blueprint-persistence.mjs';import {createHash} from 'node:crypto'
const source=await readFile('src/main.ts','utf8'),css=await readFile('src/styles.css','utf8'),html=await readFile('index.html','utf8'),build=await readFile('scripts/build.mjs','utf8'),core=await readFile('api/core.mjs','utf8'),persistence=await readFile('api/first-blueprint-persistence.mjs','utf8');const bp=deterministicBlueprint({business_model:'Services or consulting',target_customer:'Solo founders or experts'})
test('five workshops ask only strategy-shaping questions',()=>{for(const name of ['The Business','The Customer','The Offer','Growth','The Next 90 Days'])assert.match(source,new RegExp(`title:'${name}'`));const ids=[...source.matchAll(/q\('([^']+)'/g)].map(x=>x[1]);assert.equal(ids.length,15);assert.equal(new Set(ids).size,15);assert.equal(ids.length/titles.length,3);for(const id of ids)assert.match(core,new RegExp(`'${id}'`))})
test('journey is conversational and one question per screen',()=>{assert.match(source,/A PRIVATE FOUNDER SESSION/);assert.match(source,/ABOUT \$\{remaining\} MIN LEFT/);assert.match(source,/← Back/);assert.match(source,/Saves automatically/);assert.equal((source.match(/id=\"answer\"/g)||[]).length,1);assert.match(source,/function intro/);assert.match(source,/function bridge/)})
test('answers persist, recover safely and resume',()=>{assert.match(source,/localStorage\.setItem/);assert.match(source,/try\{const x=JSON\.parse/);assert.match(source,/function resume/);assert.match(source,/addEventListener\('input'/)})
test('report uses a concise executive structure',()=>{assert.equal(bp.sections.length,5);assert.deepEqual(bp.sections.map(x=>x.title),titles);assert(validBlueprint(bp));for(const s of bp.sections)assert.deepEqual(Object.keys(s),['title','observation','insight','recommendation','immediateAction']);for(const label of ['Why this matters','Do this next'])assert.match(source,new RegExp(label))})
test('engine connects workshops into decisions and selective services',()=>{assert(bp.patterns.length);assert.equal(bp.strategicSummary.length,3);assert.equal(bp.topPriorities.length,5);assert.deepEqual(Object.keys(bp.actionPlan),['weeks1to2','weeks3to6','weeks7to12']);assert(bp.recommendedServices.length<=2);for(const label of ['From Daniel','Priorities','90-Day Plan','Where Daniel can help'])assert.match(source,new RegExp(label,'i'))})
test('PDF preserves the canonical report',()=>{const output=pdf(bp).toString();assert.match(output,/Your Founder Strategy/);assert.match(output,/\/Count 8/);assert.match(output,/INSIGHT/);assert.match(output,/90-Day Action Plan/);assert.equal(canonical(bp),canonical(JSON.parse(JSON.stringify(bp))))})
test('email uses the canonical payload',()=>{assert.match(core,/validBlueprint/);assert.match(source,/blueprint:bp/);assert.match(source,/\/api\/email/);assert.match(source,/data-email-form/);assert.match(source,/Sending…/)})
test('responsive premium layouts and product states are present',()=>{assert.match(css,/@media\(max-width:760px\)/);assert.match(css,/report-section dl/);assert.match(css,/question-meta/);assert.match(css,/email-dialog/);assert.match(source,/data-contact/);assert.match(source,/Preparing PDF…/)})
test('production HTML references compiled assets',()=>{assert.match(html,/\/assets\/styles\.css/);assert.match(html,/\/assets\/main\.js/);assert.match(build,/dist\/assets\/styles\.css/)})
test('accessibility affordances are present',()=>{assert.match(source,/Skip to content/);assert.match(source,/role=\"progressbar\"/);assert.match(source,/role=\"alert\"/);assert.match(css,/:focus-visible/)})
const invoke=async(handler,{method='POST',body={}}={})=>{let status=200,payload,headers={};const req={method,body};const res={status(code){status=code;return this},json(value){payload=value;return this},send(value){payload=value;return this},setHeader(key,value){headers[key]=value}};await handler(req,res);return{status,payload,headers}}
test('API errors are explicit',async()=>{assert.equal((await invoke(generateHandler,{method:'GET'})).status,405);assert.equal((await invoke(generateHandler,{body:{}})).status,400);assert.equal((await invoke(pdfHandler,{body:{}})).status,400);assert.equal((await invoke(emailHandler,{body:{email:'bad'}})).status,400);assert.equal((await invoke(contactHandler,{body:{}})).status,400)})
test('generation, PDF and consultation complete contracts',async()=>{const generated=await invoke(generateHandler,{body:{answers:{audience:'founders'}}});assert.equal(generated.status,200);assert(validBlueprint(generated.payload));const document=await invoke(pdfHandler,{body:{blueprint:generated.payload}});assert.equal(document.status,200);assert.equal(document.headers['content-type'],'application/pdf');assert(document.payload.subarray(0,4).equals(Buffer.from('%PDF')));assert.equal((await invoke(contactHandler,{body:{name:'Alex',email:'a@b.co',message:'Strategy discussion'}})).status,200)})
test('scoring remains absent',()=>{assert.doesNotMatch(source,/score\s*[=:]/i);assert.doesNotMatch(core,/score\s*[=:]/i)})
test('finalized hypothesis is passed exactly with its persisted binding',async()=>{const hypothesis='Exact punctuation — and spacing stay unchanged.';const calls=[];const candidate={assessmentType:'BRAND_BLUEPRINT',status:'COMPLETED',assessmentFingerprint:'fingerprint-123',firstBlueprintPriority:'POSITIONING',activationReady:false};const fetchImpl=async(url,options={})=>{calls.push({url,options});if(calls.length===1)return new Response(JSON.stringify({candidates:[candidate]}),{status:200});if(calls.length===2)return new Response(JSON.stringify({replay:false}),{status:200});return new Response(JSON.stringify({candidates:[{...candidate,activationReady:true}]}),{status:200})};const result=await persistFirstBlueprintInterpretation({submissionId:'submission/a',firstBlueprintHypothesis:hypothesis,baseUrl:'https://engine.example/',token:'secret-token',fetchImpl});const posted=JSON.parse(calls[1].options.body);assert.deepEqual(posted,{submissionId:'submission/a',assessmentFingerprint:'fingerprint-123',firstBlueprintPriority:'POSITIONING',firstBlueprintHypothesis:hypothesis});assert.match(calls[0].url,/submissionId=submission%2Fa$/);assert.equal(result.activationReady,true);assert.equal(calls.every(call=>call.options.headers.authorization==='Bearer secret-token'),true)})
test('idempotent replay is successful and conflicts fail closed without retry',async()=>{const candidate={assessmentType:'BRAND_BLUEPRINT',status:'COMPLETED',assessmentFingerprint:'fp',firstBlueprintPriority:'OFFER'};let calls=0;const replayFetch=async()=>new Response(JSON.stringify(++calls===1?{candidates:[candidate]}:{replay:true}),{status:200});const replay=await persistFirstBlueprintInterpretation({submissionId:'id',firstBlueprintHypothesis:'Words.',baseUrl:'https://engine.example',token:'token',fetchImpl:replayFetch,confirmActivation:false});assert.equal(replay.replay,true);for(const code of ['INTERPRETATION_BINDING_MISMATCH','INTERPRETATION_ALREADY_FROZEN']){calls=0;const conflictFetch=async()=>{calls++;return calls===1?new Response(JSON.stringify({candidates:[candidate]}),{status:200}):new Response(JSON.stringify({code}),{status:409})};await assert.rejects(()=>persistFirstBlueprintInterpretation({submissionId:'id',firstBlueprintHypothesis:'Words.',baseUrl:'https://engine.example',token:'token',fetchImpl:conflictFetch,confirmActivation:false}),error=>error instanceof InterpretationConflictError&&error.code===code);assert.equal(calls,2)}})
test('candidate lookup requires exactly one completed Brand Blueprint',async()=>{const fetchImpl=async()=>new Response(JSON.stringify({candidates:[]}),{status:200});await assert.rejects(()=>persistFirstBlueprintInterpretation({submissionId:'id',firstBlueprintHypothesis:'Words.',baseUrl:'https://engine.example',token:'token',fetchImpl,confirmActivation:false}),/exactly one/)})
test('Daniel token remains server-only and building state prevents duplicate submission',()=>{assert.doesNotMatch(source,/DANIEL_TOKEN/);assert.doesNotMatch(html,/DANIEL_TOKEN/);assert.doesNotMatch(build,/DANIEL_TOKEN/);assert.match(persistence,/process\.env\.DANIEL_TOKEN/);assert.match(source,/if\(generating\)return/);assert.match(source,/disabled>Building Blueprint/);assert.match(source,/This may take a few moments/);assert.match(css,/animation:spin/)})
test('frozen V2 question definitions and unrelated TradeBuilt product remain untouched',()=>{const questionBlock=source.slice(source.indexOf('const workshops:'),source.indexOf('const total='));assert.equal(createHash('sha256').update(questionBlock).digest('hex'),'3a9098bd3bc87cf25528f74cad11121d984a2acda1eb09f70fe41e428101671d');assert.doesNotMatch(source+core+persistence,/TradeBuilt/i)})
