import test from 'node:test';import assert from 'node:assert/strict';import {deterministicBlueprint,canonical,pdf,titles,validBlueprint} from '../api/core.mjs';import {readFile} from 'node:fs/promises'
import generateHandler from '../api/generate.mjs';import pdfHandler from '../api/pdf.mjs';import emailHandler from '../api/email.mjs';import contactHandler from '../api/contact.mjs'
const source=await readFile('src/main.ts','utf8'),css=await readFile('src/styles.css','utf8'),html=await readFile('index.html','utf8'),build=await readFile('scripts/build.mjs','utf8'),awaitCore=await readFile('api/core.mjs','utf8');const bp=deterministicBlueprint({business:'A useful company',audience:'independent founders'})
test('all five workshops are complete',()=>{for(const name of ['Business Foundation','Market Position','Brand Strategy','Commercial Growth','Blueprint Roadmap'])assert.match(source,new RegExp(name));assert.equal((source.match(/title:'/g)||[]).length>=5,true)})
test('all 21 questions are unique and connected to output strategy',()=>{const ids=[...source.matchAll(/\{id:'([^']+)'/g)].map(x=>x[1]);assert.equal(ids.length,21);assert.equal(new Set(ids).size,21);for(const id of ids)assert.match(awaitCore,new RegExp(`answers,'${id}'`))})
test('answers persist locally, recover from corrupt storage and resume',()=>{assert.match(source,/localStorage\.setItem/);assert.match(source,/try\{const value=JSON\.parse/);assert.match(source,/function resume/);assert.match(source,/addEventListener\('input'/)})
test('generation produces the complete canonical Blueprint',()=>{assert.equal(bp.sections.length,22);assert.deepEqual(bp.sections.map(x=>x.title),titles);assert(validBlueprint(bp))})
test('PDF uses the same Blueprint content and premium multi-page system',()=>{const output=pdf(bp).toString();assert.match(output,/Your Brand Blueprint/);assert.match(output,/independent founders/);assert.match(output,/\/Count 10/);assert.match(output,/0\.09 0\.25 0\.21 rg/);assert.equal(canonical(bp),canonical(JSON.parse(JSON.stringify(bp))))})
test('email and consultation flows preserve canonical payload',async()=>{assert.match(await readFile('api/email.mjs','utf8'),/validBlueprint/);assert.match(source,/blueprint:bp/);assert.match(source,/\/api\/contact/)})
test('mobile layout is present',()=>assert.match(css,/@media\(max-width:760px\)/))
test('production HTML loads every compiled asset',()=>{assert.match(html,/<link rel="stylesheet" href="\/assets\/styles\.css"/);assert.match(html,/<script type="module" src="\/assets\/main\.js"/);assert.match(build,/dist\/assets\/styles\.css/);assert.match(build,/Production asset is missing or unreferenced/)})
test('accessibility affordances are present',()=>{assert.match(source,/Skip to content/);assert.match(source,/role="progressbar"/);assert.match(source,/role="alert"/);assert.match(css,/:focus-visible/)})
const invoke=async(handler,{method='POST',body={}}={})=>{let status=200,payload,headers={};const req={method,body};const res={status(code){status=code;return this},json(value){payload=value;return this},send(value){payload=value;return this},setHeader(key,value){headers[key]=value}};await handler(req,res);return{status,payload,headers}}
test('API method and payload errors are explicit',async()=>{assert.equal((await invoke(generateHandler,{method:'GET'})).status,405);assert.equal((await invoke(generateHandler,{body:{}})).status,400);assert.equal((await invoke(pdfHandler,{body:{}})).status,400);assert.equal((await invoke(emailHandler,{body:{email:'bad'}})).status,400);assert.equal((await invoke(contactHandler,{body:{}})).status,400)})
test('generation and PDF endpoints complete the production contract',async()=>{const generated=await invoke(generateHandler,{body:{answers:{audience:'founders'}}});assert.equal(generated.status,200);assert(validBlueprint(generated.payload));const document=await invoke(pdfHandler,{body:{blueprint:generated.payload}});assert.equal(document.status,200);assert.equal(document.headers['content-type'],'application/pdf');assert(document.payload.subarray(0,4).equals(Buffer.from('%PDF')))})
test('scoring is intentionally absent from the qualitative strategy journey',()=>{assert.doesNotMatch(source,/score\s*[=:]/i);assert.doesNotMatch(awaitCore,/score\s*[=:]/i)})
