type Question={id:string;prompt:string;guide:string;placeholder:string}
type Workshop={title:string;focus:string;intro:string;questions:Question[]}
type ReportSection={title:string;headline:string;insight:string;recommendation:string;nextAction:string}
type Blueprint={title:string;sections:ReportSection[];closing:string[]}
const q=(id:string,prompt:string,guide:string,placeholder:string):Question=>({id,prompt,guide,placeholder})
const workshops:Workshop[]=[
 {title:'Business Foundation',focus:'Purpose, proof and ambition',intro:'Let’s begin beneath the brand. We’ll establish what is true, valuable and worth building.',questions:[q('business','What are you really building?','Go beyond the product. Describe the change you create.','I’m building…'),q('proof','What is your strongest proof that people value it?','Use a real signal: demand, payment, retention or referral.','The strongest proof is…'),q('purpose','Why is this business worth building?','Name the contribution, not the slogan.','It is worth building because…'),q('vision','What should be true in five years?','Describe the business at its best.','In five years…'),q('success','How will you know the business is succeeding?','Choose the measure that matters most.','Success will mean…')]},
 {title:'Market Position',focus:'Audience, problem and advantage',intro:'Strong businesses make deliberate choices. Let’s define the customer, buying moment and territory you can own.',questions:[q('audience','Who is the one customer you most want to win?','Picture a recognisable person or business stage.','Our best-fit customer is…'),q('problem','What is happening when they need you?','Take me to the urgent trigger moment.','They need us when…'),q('alternatives','What would they choose if you did not exist?','Include competitors, workarounds and inaction.','Without us, they would…'),q('advantage','What can you deliver that alternatives cannot?','Focus on credible method, judgement or access.','Our advantage is…'),q('category','What market territory should you be known for?','Choose a clear space, not a broad category.','We should be known for…')]},
 {title:'Brand Strategy',focus:'Promise, personality and message',intro:'Now we turn commercial truth into a brand people remember. We’ll define the promise and character that make it yours.',questions:[q('transformation','What changes after a customer chooses you?','Describe the practical before and after.','They move from… to…'),q('promise','What promise can you keep every time?','Make it meaningful, specific and deliverable.','Customers can rely on us to…'),q('personality','How should it feel to deal with you?','Choose three qualities that guide behaviour.','It should feel…'),q('message','What belief should your brand lead with?','Offer customers a useful way to see their world.','We believe…'),q('proof_story','Which story best proves your promise?','Choose one concrete customer or founder example.','The story that proves it is…')]},
 {title:'Commercial Growth',focus:'Journey, trust and opportunity',intro:'Brand must change behaviour. Let’s connect attention, trust and revenue without adding noise.',questions:[q('journey','How does a stranger become a loyal customer?','Trace the shortest honest path from discovery to return.','They first find us…'),q('trust','What must they see before they trust you?','Name the proof or experience that removes doubt.','Trust grows when…'),q('offer','What would make your offer easier to buy?','Consider clarity, packaging, risk and price.','The offer becomes easier when…'),q('growth','Where is the most credible next source of growth?','Choose the opportunity where you have a right to win.','The strongest opportunity is…'),q('automation','Where could automation create useful capacity?','Protect human judgement and relationships.','We could automate…')]},
 {title:'Action Plan',focus:'Priorities, assets and action',intro:'The final workshop is about disciplined choice. We’ll set one outcome and make the first moves concrete.',questions:[q('constraint','What could most easily slow progress?','Name the real bottleneck.','The main constraint is…'),q('priority','What must be materially better in 90 days?','Choose one measurable outcome.','In 90 days…'),q('ip','What valuable know-how should you package or protect?','Consider methods, data, content and systems.','A valuable asset is…'),q('stop','What will you stop or defer?','Create space for the priority.','We will stop…'),q('first_action','What is the first action you will take this week?','Make it specific enough to schedule.','This week I will…')]}
]
const root=document.querySelector<HTMLDivElement>('#root')!,storageKey='brand-blueprint-v2';let workshopIndex=0,questionIndex=0
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));const mark='<span class="logo-mark">DB</span>'
function load(){try{const x=JSON.parse(localStorage.getItem(storageKey)||'{}');return x&&typeof x==='object'&&!Array.isArray(x)?x:{}}catch{return {}}}let answers:Record<string,string>=load();const save=()=>localStorage.setItem(storageKey,JSON.stringify(answers))
const shell=(body:string)=>`<a class="skip" href="#content">Skip to content</a><header class="site-header"><a class="logo" href="#" data-home>${mark}<span>Brand Blueprint</span></a><div class="founder-signoff"><span>Created and guided by</span><strong>Daniel</strong></div></header><main id="content">${body}</main><footer><div>${mark}<strong>Daniel</strong><span>Founder, Brand Blueprint</span></div><p>Think clearly. Build meaningfully. Grow commercially.</p><small>© 2026 Brand Blueprint</small></footer>`
function bindHome(){document.querySelectorAll('[data-home]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();home()}))}
function home(){root.innerHTML=shell(`<section class="hero"><div class="hero-copy"><span class="eyebrow">A PRIVATE STRATEGY SESSION WITH DANIEL</span><h1>Build the business<br><em>before the brand.</em></h1><p class="hero-lead">Five focused workshops. One clear, commercially useful Blueprint.</p><div class="hero-actions"><button class="primary premium-cta" data-start>${Object.keys(answers).length?'Continue Your Blueprint':'Start Your Blueprint'} <i>↗</i></button><span>Free · confidential · about 15 minutes</span></div></div><aside class="hero-principle"><span class="eyebrow">DANIEL’S PRINCIPLE</span><p>“A beautiful identity cannot rescue an unclear business.”</p><div><span class="portrait">DB</span><span><strong>Daniel</strong><small>Founder & commercial strategist</small></span></div></aside></section><section class="blueprint"><div class="blueprint-intro"><span class="eyebrow">FIVE FOCUSED WORKSHOPS</span><h2>Clear thinking, made actionable.</h2><p>One question at a time, with your work saved automatically.</p></div><div class="blueprint-steps">${workshops.map((w,i)=>`<article><span>0${i+1}</span><div><small>${esc(w.focus)}</small><h3>${esc(w.title)}</h3></div></article>`).join('')}</div></section>`);document.querySelector('[data-start]')!.addEventListener('click',resume);bindHome()}
function resume(){const all=workshops.flatMap((w,wi)=>w.questions.map((x,qi)=>({x,wi,qi}))),first=all.find(v=>!answers[v.x.id]?.trim());if(!first)return generate();workshopIndex=first.wi;questionIndex=first.qi;question()}
function question(){const w=workshops[workshopIndex],item=w.questions[questionIndex],done=workshopIndex*5+questionIndex,remaining=Math.max(1,Math.ceil((25-done)*.6)),value=answers[item.id]||'';root.innerHTML=shell(`<div class="session-top"><button class="back" data-back>← Previous</button><div class="session-progress"><div><span>WORKSHOP ${workshopIndex+1} OF 5</span><strong>${esc(w.title)}</strong></div><div class="progress-track" role="progressbar" aria-label="Blueprint completion" aria-valuenow="${done}" aria-valuemin="0" aria-valuemax="25"><i style="width:${done/25*100}%"></i></div><small>${done}/25</small></div><button class="save" data-home>Save & exit</button></div><section class="question-layout"><aside class="founder-intro"><span class="mini-portrait">DB</span><span class="eyebrow">PRIVATE SESSION</span><p>${esc(w.intro)}</p></aside><div class="question-panel"><div class="question-meta"><span>${esc(w.focus.toUpperCase())} · ${questionIndex+1} OF 5</span><span>ABOUT ${remaining} MIN LEFT</span></div><h1>${esc(item.prompt)}</h1><p class="strategist-note" id="guide">${esc(item.guide)}</p><label class="sr-only" for="answer">Your answer</label><textarea id="answer" maxlength="650" aria-describedby="guide save-status" placeholder="${esc(item.placeholder)}">${esc(value)}</textarea><small id="save-status" class="save-status" aria-live="polite">${value?'Saved on this device':'Saved automatically as you type'}</small><p class="error" role="alert" hidden>Please share an answer before we continue.</p><div class="question-actions"><button class="primary continue" data-next>${done===24?'Create my Blueprint':'Next'} →</button></div></div></section>`);const textarea=document.querySelector<HTMLTextAreaElement>('#answer')!;textarea.addEventListener('input',()=>{answers[item.id]=textarea.value.slice(0,650);save();document.querySelector('#save-status')!.textContent='Saved on this device'});document.querySelector('[data-next]')!.addEventListener('click',next);document.querySelector('[data-back]')!.addEventListener('click',back);bindHome();textarea.focus()}
function next(){const item=workshops[workshopIndex].questions[questionIndex],value=document.querySelector<HTMLTextAreaElement>('#answer')!.value.trim();if(!value){document.querySelector<HTMLElement>('.error')!.hidden=false;return}answers[item.id]=value;save();if(questionIndex<4){questionIndex++;question()}else if(workshopIndex<4){workshopIndex++;questionIndex=0;question()}else generate()}
function back(){if(questionIndex)questionIndex--;else if(workshopIndex){workshopIndex--;questionIndex=4}else return home();question()}
async function generate(){root.innerHTML=shell(`<section class="transition" role="status"><span class="spinner"></span><h1>Daniel is drafting your Blueprint.</h1><p>Turning your choices into a focused strategic direction.</p></section>`);try{const r=await fetch('/api/generate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({answers}),signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error();render(await r.json())}catch{root.innerHTML=shell(`<section class="transition" role="alert"><h1>Your answers are safe.</h1><p>We couldn’t draft the report just now.</p><button class="primary" data-retry>Try again</button></section>`);document.querySelector('[data-retry]')!.addEventListener('click',generate);bindHome()}}
function render(bp:Blueprint){sessionStorage.setItem('blueprint',JSON.stringify(bp));root.innerHTML=shell(`<section class="results-hero"><div class="results-hero-inner"><span class="eyebrow">YOUR BRAND BLUEPRINT</span><h1>${esc(bp.title)}</h1><p>Five strategic decisions, shaped from your private session with Daniel.</p><div class="blueprint-actions"><button class="primary" data-pdf>Download PDF ↓</button><button class="outline" data-email>Email Blueprint →</button></div></div><div class="report-edition"><span>PRIVATE STRATEGY DOCUMENT</span><strong>V2</strong><small>DANIEL · 2026</small></div></section><section class="report"><div class="report-rule"><span>STRATEGIC REPORT</span><span>FIVE WORKSHOPS · ONE PLAN</span></div><div class="report-body">${bp.sections.map((s,i)=>`<article class="report-section"><span>0${i+1}</span><div><small>${esc(s.title)}</small><h2>${esc(s.headline)}</h2><dl><div><dt>Insight</dt><dd>${esc(s.insight)}</dd></div><div><dt>Recommendation</dt><dd>${esc(s.recommendation)}</dd></div><div class="next-action"><dt>Next Action</dt><dd>${esc(s.nextAction)}</dd></div></dl></div></article>`).join('')}</div><section class="closing"><span class="closing-mark">DB</span><div><h2>${esc(bp.closing[0])}</h2><p>${bp.closing.slice(1).map(esc).join('<br>')}</p></div></section><section class="contact"><div class="contact-intro"><span class="eyebrow">NEXT STEPS</span><h2>Talk it through with Daniel.</h2></div><form data-contact><label>Name<input name="name" required></label><label>Email<input name="email" type="email" required></label><label>What would make this useful?<textarea name="message" required></textarea></label><button class="primary">Request a consultation →</button><p role="status"></p></form></section></section>`);document.querySelector('[data-pdf]')!.addEventListener('click',()=>download(bp));document.querySelector('[data-email]')!.addEventListener('click',()=>email(bp));document.querySelector<HTMLFormElement>('[data-contact]')!.addEventListener('submit',contact);bindHome()}
async function download(bp:Blueprint){const r=await fetch('/api/pdf',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({blueprint:bp})});if(!r.ok)return alert('The PDF could not be prepared.');const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download='brand-blueprint.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
async function email(bp:Blueprint){const address=prompt('Where should I send your Blueprint?')?.trim();if(!address)return;const r=await fetch('/api/email',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:address,blueprint:bp})});alert(r.ok?'Your Blueprint is on its way.':'We could not send it. Please check the address and try again.')}
async function contact(e:Event){e.preventDefault();const form=e.currentTarget as HTMLFormElement,status=form.querySelector('[role=status]')!;status.textContent='Sending…';const r=await fetch('/api/contact',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(form)))});status.textContent=r.ok?'Thank you. Daniel will be in touch personally.':'That did not send. Please try again.';if(r.ok)form.reset()}
home()
