export const titles=['Founder Perspective','Business Purpose','Vision','Ideal Audience','Core Problem','Strategic Positioning','Competitive Advantage','Offer and Transformation','Brand Promise','Brand Personality','Messaging Direction','Naming and Domain Considerations','Customer Journey','Trust and Experience Principles','Business Operating Priorities','Growth Opportunities','AI and Automation Opportunities','Intellectual Property and Commercialisation Considerations','90-Day Strategic Roadmap','Recommended Brand Blueprint Services','Daniel’s Strategic Recommendation','Next Steps']
const clean=(v)=>String(v||'').replace(/\s+/g,' ').trim().slice(0,800)
const a=(answers,key,fallback)=>clean(answers[key])||fallback
export function deterministicBlueprint(answers={}){const audience=a(answers,'audience','the best-fit customer you choose to serve');const problem=a(answers,'problem','an urgent, costly problem they already recognise');const advantage=a(answers,'advantage','a distinctive method supported by visible proof');const priority=a(answers,'priority','make the core proposition clearer and easier to buy');const content=[
 `Daniel’s view: ${a(answers,'business','The opportunity is to build a focused business around a meaningful customer outcome')}. The strongest evidence today is ${a(answers,'proof','the customer proof gathered so far')}. The strongest route forward is disciplined choice, not more activity.`,a(answers,'purpose','Build a commercially sound business that creates a worthwhile change for its customers.'),a(answers,'vision','In five years the business is known, trusted and operationally ready to grow without losing its character.'),audience,problem,
 `Position the business as the credible choice for ${audience}, especially when ${problem.toLowerCase()}. Customers otherwise choose ${a(answers,'alternatives','familiar competitors, internal workarounds or inaction')}. Lead with the outcome, then substantiate it with the method and proof.`,advantage,a(answers,'transformation','Turn a frustrating starting point into a clear, confident and valuable result.'),a(answers,'promise','Make a specific promise the team can keep consistently and customers can repeat.'),a(answers,'personality','Clear, assured and human. Every expression should feel expert without becoming distant.'),a(answers,'message','Lead with a useful point of view, connect it to the customer’s present tension, and prove the commercial outcome.'),a(answers,'naming','Choose a memorable, extensible name; check trade marks, company registers, search confusion and appropriate domains before committing.'),a(answers,'journey','Create one coherent path from discovery to evaluation, purchase, delivery and advocacy, with a clear next step at every stage.'),a(answers,'trust','Make expertise visible through proof, transparent expectations, responsive communication and a consistently thoughtful delivery experience.'),`Remove the primary constraint—${a(answers,'constraint','focus and capacity')}—before adding channels. Assign an owner, a measure and a weekly decision rhythm to the ninety-day priority.`,a(answers,'growth','Deepen the strongest current route to market before diversifying; test the opportunity with a bounded commercial experiment.'),`Start with ${a(answers,'automation','repetitive research, administration and follow-up')}. Automate preparation and routine movement of information, but retain human judgement for strategy, promises and relationships.`,`${a(answers,'ip','Document the distinctive method and assets that make delivery repeatable')}. Seek qualified legal advice on trade marks, ownership and licensing before commercial commitments.`,
 `Days 1–30: decide the position, proposition and success measure. Days 31–60: build proof, messaging and the priority customer journey. Days 61–90: launch one measured growth experiment and review results. The outcome: ${priority}.`,
 `Begin with a Positioning Intensive to resolve the highest-value strategic choices. Follow with a Brand Blueprint Partnership if naming, identity and messaging need to become one commercial system. The founder identified this leverage point: ${a(answers,'support','experienced outside help on the priority strategic decision')}.`,
 `My recommendation is to resist premature expansion. Make the promise more specific, the evidence more visible and the route to purchase simpler. That combination will create more value than cosmetic change alone.`,
 `Choose one accountable owner and schedule the first 90-minute working session this week. Confirm the ninety-day outcome, interview three best-fit customers, and turn their language into the first proposition draft.`]
 return{title:'Your Brand Blueprint',sections:titles.map((title,i)=>({title,content:content[i]})),closing:['Your Blueprint has been drafted.','Every successful business is built twice.','First as a blueprint.','Then in the real world.','','Today, you completed the first build.','Now it’s time to build the second.']}}
export const canonical=(bp)=>JSON.stringify({title:bp.title,sections:bp.sections,closing:bp.closing})
export async function generate(answers){if(process.env.OPENAI_API_KEY){try{const schema=deterministicBlueprint(answers);const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'content-type':'application/json'},signal:AbortSignal.timeout(25000),body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-5-mini',input:`You are Daniel Band, a commercially astute founder-strategist. Rewrite this complete Brand Blueprint in a direct, premium, practical voice. Preserve every title and return JSON only matching the supplied structure. Avoid assessment scores, clichés and invented facts. Answers: ${JSON.stringify(answers)}\nStructure:${JSON.stringify(schema)}`,text:{format:{type:'json_schema',name:'blueprint',strict:true,schema:{type:'object',additionalProperties:false,required:['title','sections','closing'],properties:{title:{type:'string'},sections:{type:'array',minItems:22,maxItems:22,items:{type:'object',additionalProperties:false,required:['title','content'],properties:{title:{type:'string'},content:{type:'string'}}}},closing:{type:'array',items:{type:'string'}}}}}}})});if(response.ok){const data=await response.json(),candidate=JSON.parse(data.output_text);if(validBlueprint(candidate)&&candidate.sections.every(s=>clean(s.content)))return candidate}}catch{}}
 return deterministicBlueprint(answers)}
const pdfEscape=s=>s.replace(/[\\()]/g,'\\$&').replace(/[^\x20-\x7E]/g,'')
export function pdf(bp){const lines=[bp.title,...bp.sections.flatMap(s=>[s.title,...s.content.match(/.{1,82}(?:\s|$)/g)||[]]),...bp.closing];let stream='BT /F1 10 Tf 48 780 Td 13 TL ';for(const [i,line] of lines.entries()){if(i&&i%54===0)stream+='ET BT /F1 10 Tf 48 780 Td 13 TL ';stream+=`(${pdfEscape(line)}) Tj T* `}stream+='ET';const objects=[null,'<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>',`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`,'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'];let out='%PDF-1.4\n',offset=[0];for(let i=1;i<objects.length;i++){offset[i]=out.length;out+=`${i} 0 obj\n${objects[i]}\nendobj\n`}const x=out.length;out+=`xref\n0 ${objects.length}\n0000000000 65535 f \n${offset.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n ').join('\n')}\ntrailer << /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${x}\n%%EOF`;return Buffer.from(out)}
export function validBlueprint(bp){return Boolean(bp&&bp.title==='Your Brand Blueprint'&&bp.sections?.length===22&&titles.every((t,i)=>bp.sections[i]?.title===t&&typeof bp.sections[i]?.content==='string'&&bp.sections[i].content.trim())&&Array.isArray(bp.closing)&&bp.closing.every(line=>typeof line==='string'))}
