export const titles=['Business Foundation','Market Position','Brand Strategy','Commercial Growth','The Blueprint']

const clean=value=>String(value||'').replace(/\s+/g,' ').trim().slice(0,650)
const answer=(answers,key,fallback)=>clean(answers[key])||fallback
const has=(answers,key,pattern)=>pattern.test(answer(answers,key,''))
const sentence=value=>{const v=clean(value);return v&&!/[.!?]$/.test(v)?`${v}.`:v}
const section=(title,observation,commercialInsight,blindSpot,recommendation,immediateAction,longerTermOpportunity)=>({title,observation,commercialInsight,blindSpot,recommendation,immediateAction,longerTermOpportunity})

const detectPatterns=answers=>{
 const patterns=[]
 const audience=answer(answers,'best_customer','')
 const trust=answer(answers,'reason_to_trust','')
 const limit=answer(answers,'growth_limit','')
 const adjectives=answer(answers,'five_words','')
 const premium=has(answers,'business_type',/premium|consult/i)||has(answers,'known_for',/premium|best|leading|luxury/i)
 if(audience.length<28||/everyone|anyone|businesses|people|founders and|companies and/i.test(audience))patterns.push('The intended market is broader than the business can credibly lead at once.')
 if(trust.length<35||/quality|passion|care|experience|trust/i.test(trust)&&!/[0-9]|result|case|client|award|certif/i.test(trust))patterns.push('Credibility is asserted, but the proof needed to reduce buying risk is still thin.')
 if(/time|capacity|operation|system|delivery|team|admin|process/i.test(limit))patterns.push('Growth is constrained by operating capacity before it is constrained by demand.')
 if(premium&&/affordable|cheap|budget|accessible|everyone/i.test(`${adjectives} ${answer(answers,'described_as','')} ${audience}`))patterns.push('The premium ambition and the language used to describe it are pulling in different directions.')
 if(adjectives.split(/[,;/]|\band\b/i).filter(Boolean).length>5)patterns.push('The brand is trying to signal too many qualities instead of owning one commercial idea.')
 if(!patterns.length)patterns.push('The answers are directionally coherent; the commercial advantage now needs to be made visible and repeatable.')
 return patterns
}

const recommendServices=(answers,patterns)=>{
 const services=[]
 if(patterns.some(x=>/market|position|premium ambition|commercial advantage/i.test(x))||has(answers,'matters_now',/customer|brand|growth/i))services.push({name:'Positioning Intensive',reason:'To choose the most valuable audience, problem and commercial territory before more messaging is produced.'})
 if(patterns.some(x=>/proof|language|visible/i.test(x))||has(answers,'blueprint_job',/message|brand|website|communicat|position/i))services.push({name:'Brand Messaging System',reason:'To turn the chosen position into a clear promise, proof structure and sales language.'})
 if(patterns.some(x=>/operating|capacity|delivery/i.test(x))||has(answers,'matters_now',/time|system/i))services.push({name:'Commercial Systems Sprint',reason:'To remove the operational constraint and align delivery capacity with the brand promise.'})
 if(has(answers,'guidance',/offer|price|revenue|profit|commercial|growth/i)||has(answers,'matters_now',/profit|better customers/i))services.push({name:'Offer & Growth Advisory',reason:'To sharpen the offer, economics and route to higher-quality revenue.'})
 return services.slice(0,2).length?services.slice(0,2):[{name:'Quarterly Strategic Advisory',reason:'To maintain decision discipline while the 90-day priorities are implemented and evidenced.'}]
}

export function deterministicBlueprint(answers={}){
 const patterns=detectPatterns(answers),priority=answer(answers,'matters_now','focused growth')
 const sections=[
  section(titles[0],`The business exists to ${answer(answers,'existence','create a change worth paying for')}. You are building from ${answer(answers,'experience','relevant experience')}, with a clear personal conviction around ${answer(answers,'frustration','a problem worth solving')}.`,`That combination creates founder authority, but authority only becomes an asset when it shapes the offer, method and commercial model—not merely the origin story.`,`The three-year ambition—${answer(answers,'three_year_success','a successful and sustainable business')}—may be emotionally clear while the economics and the founder’s intended role remain under-defined. A compelling destination is not yet an operating model.`,`Define the business you are refusing to build, then set three conditions the ${answer(answers,'business_type','business')} must meet: revenue quality, founder involvement and delivery capacity.`,`Write a one-page three-year model with target revenue, offer mix, team shape and the work the founder will no longer perform.`,`A model designed around earned advantage can increase margins and reduce founder dependency instead of simply creating more work.`),
  section(titles[1],`The strongest buying pressure sits with ${answer(answers,'best_customer','a specific best-fit customer')} when ${answer(answers,'night_problem','an urgent problem remains unresolved')}.`,`The sale will be won by making the cost of delay—${answer(answers,'inaction_cost','a compounding commercial cost')}—more concrete than the category description. Buyers pay to change an outcome, not to admire a service.`,patterns.find(x=>/market|proof|premium/i.test(x))||`Admiring ${answer(answers,'respected_competitors','established competitors')} risks anchoring the position to conventions they already own.`,`Choose one priority buyer and one expensive problem. Build the position around a measurable consequence, then support it with ${answer(answers,'reason_to_trust','specific evidence')}.`,`Interview five recent or ideal buyers. Ask what triggered action, what delay cost them and which proof removed risk; use their repeated language.`,`A narrow entry position creates stronger referrals, clearer sales qualification and permission to expand later from a place of authority.`),
  section(titles[2],`The intended reputation is ${answer(answers,'known_for','clear and valuable expertise')}, while customers should leave with ${answer(answers,'customer_difference','a meaningful practical change')}.`,`The transformation is commercially stronger than a list of brand adjectives. It can organise the website, sales process and delivery experience around one promise.`,`“${answer(answers,'five_words','Clear, assured, useful, human and distinctive')}” describes a tone, not necessarily a difference. Unless those words force visible choices, competitors can claim them too.`,`Make the customer before-and-after the central promise. Use the stated brand qualities as internal behaviour standards and ${answer(answers,'not_brand','the rejected brand territory')} as an explicit decision boundary.`,`Audit the homepage, proposal and onboarding against the promised transformation. Remove one claim without proof and add one concrete customer outcome.`,`Repeated evidence of the same transformation will turn a desired reputation into market memory and proprietary proof.`),
  section(titles[3],`The current constraint is ${answer(answers,'growth_limit','a material growth bottleneck')}; meanwhile ${answer(answers,'time_waste','low-leverage work')} absorbs capacity that could go to ${answer(answers,'highest_value','higher-value activity')}.`,`This is an allocation problem before it is a marketing problem. More demand would amplify the bottleneck unless delivery and founder capacity improve first.`,`Automating ${answer(answers,'automate_first','repeatable administration')} before simplifying ownership and process may make unnecessary work faster rather than remove it.`,`Map the constraint from sale to delivery. Eliminate, delegate and standardise before automating; protect the recovered time for ${answer(answers,'extra_day','the neglected source of leverage')}.`,`Track the founder’s time for five working days, then remove one recurring task and reserve a weekly block for the highest-value activity.`,`Capacity reinvested consistently can become intellectual property, stronger relationships or a scalable delivery system rather than disappearing into more administration.`),
  section(titles[4],`The decision being delayed is ${answer(answers,'avoided_decision','the decision consuming attention')}, and the required 90-day evidence is ${answer(answers,'ninety_days','visible commercial progress')}.`,`The Blueprint succeeds only if ${priority.toLowerCase()} becomes a decision filter. Resolving the avoided choice will release more value than adding another initiative.`,`Seeking guidance on ${answer(answers,'guidance','the hardest strategic choice')} can become a substitute for ownership if the decision, measure and deadline remain undefined.`,`Make one governing decision now, assign one commercial measure to it and pause work that does not improve that measure within 90 days.`,`Schedule a 60-minute decision meeting this week. Record the decision, owner, success measure, first irreversible action and what will stop.`,`A disciplined decision cadence compounds: fewer priorities create faster learning, cleaner evidence and greater confidence in where to invest next.`)
 ]
 const topPriorities=[
  `Resolve ${answer(answers,'avoided_decision','the avoided strategic decision')} and make it the governing choice.`,
  `Narrow the commercial position to one best-fit buyer and one costly problem.`,
  `Turn ${answer(answers,'reason_to_trust','the strongest evidence')} into visible proof.`,
  `Remove the ${answer(answers,'growth_limit','primary operating constraint')} before increasing demand.`,
  `Measure progress against “${answer(answers,'ninety_days','a specific 90-day outcome')}.”`
 ]
 return {title:'Your Brand Blueprint',sections,patterns,strategicSummary:[`Here is my honest view. ${sentence(patterns[0])}`,`You do not need more ideas. You need a tighter commercial choice: use ${priority.toLowerCase()} to decide what receives time, proof and investment, and let the next 90 days test that choice in the market.`,`The opportunity is credible, but only if the promise, evidence and delivery system say the same thing. I would address them in that order and refuse activity that disguises a missing decision.`],topPriorities,actionPlan:{weeks1to2:[topPriorities[0],`Interview five best-fit buyers and define the commercial problem in their language.`],weeks3to6:[`Build the core promise, proof structure and sales narrative around that position.`,`Simplify the operating bottleneck and protect capacity for the highest-value work.`],weeks7to12:[`Test the position in live sales and marketing; record objections, conversion and customer quality.`,`Review the evidence, strengthen what works and set the next 90-day decision.`]},recommendedServices:recommendServices(answers,patterns)}
}

export const canonical=bp=>JSON.stringify(bp)
const fields=['observation','commercialInsight','blindSpot','recommendation','immediateAction','longerTermOpportunity']
export function validBlueprint(bp){return Boolean(bp&&bp.title==='Your Brand Blueprint'&&bp.sections?.length===5&&titles.every((t,i)=>bp.sections[i]?.title===t&&fields.every(k=>typeof bp.sections[i][k]==='string'&&bp.sections[i][k].trim()))&&bp.patterns?.length&&bp.strategicSummary?.length===3&&bp.topPriorities?.length===5&&bp.actionPlan&&['weeks1to2','weeks3to6','weeks7to12'].every(k=>bp.actionPlan[k]?.length)&&bp.recommendedServices?.length>0&&bp.recommendedServices.length<=2)}

export async function generate(answers){
 const fallback=deterministicBlueprint(answers)
 if(process.env.OPENAI_API_KEY)try{const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'content-type':'application/json'},signal:AbortSignal.timeout(25000),body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-5-mini',input:`You are Daniel, a commercially rigorous founder strategist. Analyse all 25 answers together. Interpret; never repeat or praise them. Identify contradictions, assumptions, leverage, proof gaps and operating constraints. Write directly, naturally and specifically—never mention AI. Return JSON matching this exact fallback shape. Preserve titles, keep exactly five ranked priorities, three summary paragraphs, no more than two genuinely relevant services, and connect the action plan to the analysis. Answers: ${JSON.stringify(answers)}\nRequired shape and grounded fallback: ${JSON.stringify(fallback)}`,text:{format:{type:'json_schema',name:'strategy_blueprint',strict:true,schema:blueprintSchema}}})});if(response.ok){const candidate=JSON.parse((await response.json()).output_text);if(validBlueprint(candidate))return candidate}}catch{}
 return fallback
}

const string={type:'string',minLength:1},stringList={type:'array',minItems:1,items:string}
const blueprintSchema={type:'object',additionalProperties:false,required:['title','sections','patterns','strategicSummary','topPriorities','actionPlan','recommendedServices'],properties:{title:{type:'string',const:'Your Brand Blueprint'},sections:{type:'array',minItems:5,maxItems:5,items:{type:'object',additionalProperties:false,required:['title',...fields],properties:{title:string,...Object.fromEntries(fields.map(k=>[k,string]))}}},patterns:stringList,strategicSummary:{type:'array',minItems:3,maxItems:3,items:string},topPriorities:{type:'array',minItems:5,maxItems:5,items:string},actionPlan:{type:'object',additionalProperties:false,required:['weeks1to2','weeks3to6','weeks7to12'],properties:{weeks1to2:stringList,weeks3to6:stringList,weeks7to12:stringList}},recommendedServices:{type:'array',minItems:1,maxItems:2,items:{type:'object',additionalProperties:false,required:['name','reason'],properties:{name:string,reason:string}}}}}

const pdfEscape=s=>String(s).replace(/[\\()]/g,'\\$&').replace(/[^\x20-\x7E]/g,'')
const wrap=(value,width)=>{const lines=[];let line='';for(const word of pdfEscape(value).split(/\s+/)){if(`${line} ${word}`.trim().length>width&&line){lines.push(line);line=word}else line=`${line} ${word}`.trim()}if(line)lines.push(line);return lines}
export function pdf(bp){
 const pages=[],text=(font,size,x,y,value,color='0.12 0.16 0.14')=>`${color} rg BT /${font} ${size} Tf ${x} ${y} Td (${pdfEscape(value)}) Tj ET\n`,rule=y=>`.78 .75 .69 RG 48 ${y} m 564 ${y} l S\n`,page=(title,items)=>{let y=720,s=text('F2',27,48,y,title);y-=42;for(const [label,value] of items){s+=text('F1',8,48,y,label,'.62 .46 .27');y-=20;for(const line of wrap(value,82)){s+=text('F1',10,48,y,line,'.25 .30 .27');y-=15}y-=16}return s}
 pages.push('0.09 0.25 0.21 rg 0 0 612 792 re f\n'+text('F1',8,48,720,'BRAND BLUEPRINT / PRIVATE STRATEGY DOCUMENT','0.82 0.66 0.44')+text('F2',42,48,585,bp.title,'1 1 1')+text('F1',8,48,70,'DANIEL / 2026','0.82 0.66 0.44'))
 for(const s of bp.sections)pages.push(page(s.title,[['OBSERVATION',s.observation],['COMMERCIAL INSIGHT',s.commercialInsight],['BLIND SPOT',s.blindSpot],['RECOMMENDATION',s.recommendation],['IMMEDIATE ACTION',s.immediateAction],['LONGER-TERM OPPORTUNITY',s.longerTermOpportunity]]))
 pages.push(page("Daniel's Strategic Summary",[['DANIEL',bp.strategicSummary.join(' ')],['TOP 5 PRIORITIES',bp.topPriorities.map((x,i)=>`${i+1}. ${x}`).join(' ')]]))
 pages.push(page('90-Day Action Plan',[['WEEKS 1-2',bp.actionPlan.weeks1to2.join(' ')],['WEEKS 3-6',bp.actionPlan.weeks3to6.join(' ')],['WEEKS 7-12',bp.actionPlan.weeks7to12.join(' ')],['RECOMMENDED SERVICES',bp.recommendedServices.map(x=>`${x.name}: ${x.reason}`).join(' ')]]))
 const pageStart=3,contentStart=pageStart+pages.length,fontRegular=contentStart+pages.length,fontDisplay=fontRegular+1,objects=[null,'<< /Type /Catalog /Pages 2 0 R >>',`<< /Type /Pages /Kids [${pages.map((_,i)=>`${pageStart+i} 0 R`).join(' ')}] /Count ${pages.length} >>`];for(let i=0;i<pages.length;i++)objects.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 ${fontRegular} 0 R /F2 ${fontDisplay} 0 R >> >> /Contents ${contentStart+i} 0 R >>`);for(const stream of pages)objects.push(`<< /Length ${Buffer.byteLength(stream)} >>\nstream\n${stream}endstream`);objects.push('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>','<< /Type /Font /Subtype /Type1 /BaseFont /Times-Roman >>');let out='%PDF-1.4\n',offset=[0];for(let i=1;i<objects.length;i++){offset[i]=Buffer.byteLength(out);out+=`${i} 0 obj\n${objects[i]}\nendobj\n`}const x=Buffer.byteLength(out);out+=`xref\n0 ${objects.length}\n0000000000 65535 f \n${offset.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n ').join('\n')}\ntrailer << /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${x}\n%%EOF`;return Buffer.from(out)
}
